# -*- coding: utf-8 -*-
"""Copy of GrowthAnalysisModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RK1vDuRqh4JsafPmTfOCYNvGslua86F7
"""

#import libraries.
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import VGG16

#connect driver with colab | mount together
from google.colab import drive
drive.mount('/content/drive')

#do preprosessing with ImageDataGenerator | training dataset
IMAGE_SIZE = 224
CHANNELS = 3
train_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

train_generator = train_datagen.flow_from_directory(
    '/content/drive/MyDrive/fish-growth/newDataSet/train',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse'
)

#initializing classes
train_generator.class_indices

class_names = list(train_generator.class_indices.keys())
class_names

#check image size
for image_batch, label_batch in train_generator:
  print(image_batch.shape)
  break

#do preprosessing with ImageDataGenerator | validation dataset
IMAGE_SIZE = 224
CHANNELS = 3
valid_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

validation_generator = valid_datagen.flow_from_directory(
    '/content/drive/MyDrive/fish-growth/newDataSet/val',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse'
)

#do preprosessing with ImageDataGenerator | test dataset
IMAGE_SIZE = 224
CHANNELS = 3
test_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

test_generator = test_datagen.flow_from_directory(
    '/content/drive/MyDrive/fish-growth/newDataSet/test',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse'
)

#import vgg-16 model
input_shape=( IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 6


base_model = VGG16(weights="imagenet", include_top=False, input_shape=input_shape)
base_model.trainable = False

#use model to train
model = models.Sequential([
    base_model,
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax')  
])

model.summary()

#optimizing 
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

#243/32

#training model with vgg-16 | epoch 30
history = model.fit(
    train_generator,
    steps_per_epoch=8,
    batch_size=32,
    validation_data=validation_generator,
    validation_steps=1,
    verbose=1,
    epochs=30
)

scores = model.evaluate(test_generator)

scores

history

history.params

history.history.keys()

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

#generating validation and training Loss & accuracy
plt.figure(figsize=(8,8))
plt.subplot(1, 2, 1)
plt.plot(range(30), acc, label='Training Accuracy')
plt.plot(range(30), val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(range(30), loss, label='Training Loss')
plt.plot(range(30), val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')

import numpy as np
for image_batch, label_batch in test_generator:
    first_image = image_batch[0]
    first_label = int(label_batch[0])
    
    print("first image to predict")
    plt.imshow(first_image)
    print("actual label:",class_names[first_label])
    
    batch_prediction = model.predict(image_batch)
    print("predicted label:",class_names[np.argmax(batch_prediction[0])])
    
    break

def predict(model, img):
    img_array = tf.keras.preprocessing.image.img_to_array(images[i])
    img_array = tf.expand_dims(img_array, 0)
    
    predictions = model.predict(img_array)
    
    predicted_class = class_names[np.argmax(predictions[0])]
    confidence = round(100 * (np.max(predictions[0])), 2)
    return predicted_class, confidence

plt.figure(figsize=(15, 15))
for images, labels in test_generator:
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i])
        predicted_class, confidence = predict(model, images[i])
        actual_class = class_names[int(labels[i])]
        plt.title(f"Actual: {actual_class},\n Predicted: {predicted_class}.\n Confidence: {confidence}%")
        plt.axis("off")
    break

model_version=16
model.save(f"/content/drive/MyDrive/fish-growth/models/{model_version}.h5")

